name: Prexel Server Deply

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.EMAIL}}
          heroku_app_name: ""
        
      - name: "Move to prexel server"
        run: cd prexel-server
          
      - name: "Login to heroku registry"
        run: heroku container:login

      - name: "Build and push to heroku registry"
        run: heroku container:push web --app ${{secrets.HEROKU_APP_NAME}}

      - name: "Releases the container"
        run: heroku container:release web --app ${{secrets.HEROKU_APP_NAME}}
